"""Firewall rejection reason codes (R6.41).

Exactly the 24 codes the firewall may record. The recorded code is deterministic
because the firewall's checks are ordered and first-match wins (R6.42).
"""

from enum import StrEnum

__all__ = ["RejectionReason"]


class RejectionReason(StrEnum):
    """The 24 rejection reason codes of R6.41."""

    UNPARSEABLE = "UNPARSEABLE"
    NOT_SELECT = "NOT_SELECT"
    MULTIPLE_STATEMENTS = "MULTIPLE_STATEMENTS"
    SEPARATOR_PRESENT = "SEPARATOR_PRESENT"
    EMPTY_STATEMENT = "EMPTY_STATEMENT"
    FORBIDDEN_KEYWORD = "FORBIDDEN_KEYWORD"
    COMMENT_PRESENT = "COMMENT_PRESENT"
    DATA_MODIFYING_CTE = "DATA_MODIFYING_CTE"
    NESTED_DML = "NESTED_DML"
    SELECT_INTO = "SELECT_INTO"
    LOCKING_CLAUSE = "LOCKING_CLAUSE"
    UNAPPROVED_SCHEMA = "UNAPPROVED_SCHEMA"
    SYSTEM_CATALOG_REFERENCE = "SYSTEM_CATALOG_REFERENCE"
    UNAPPROVED_TABLE = "UNAPPROVED_TABLE"
    UNAPPROVED_COLUMN = "UNAPPROVED_COLUMN"
    UNAPPROVED_FUNCTION = "UNAPPROVED_FUNCTION"
    FORBIDDEN_FUNCTION = "FORBIDDEN_FUNCTION"
    MISSING_LIMIT = "MISSING_LIMIT"
    LIMIT_EXCEEDS_ROW_CAP = "LIMIT_EXCEEDS_ROW_CAP"
    NON_LITERAL_LIMIT = "NON_LITERAL_LIMIT"
    NON_LITERAL_OFFSET = "NON_LITERAL_OFFSET"
    MISSING_JOIN_PREDICATE = "MISSING_JOIN_PREDICATE"
    COMPLEXITY_EXCEEDED = "COMPLEXITY_EXCEEDED"
    UNPARAMETERIZED_LITERAL = "UNPARAMETERIZED_LITERAL"
